### ISSUE TITLE
`SyntaxError: Unexpected token 'export'` in `node_modules/zustand-computed/dist/index.mjs:87`

### ISSUE THREAD

**Issue by SouroucheB** [chrisvander/zustand-computed#37]
Hello there,

I'm getting this error when I run a very basic test in Jest :

```typescript
describe('Page', () => {
  it('should render the page', async () => {
    render(<Page />)
  })
})
```

I saw that we are using `zustand-computed` in stores that are used in the tested page and removing them is fixing the issue.

FYI, I've tried to mock zustand, I also try to update Jest config to tell him to transform the `zustand-computed` mjs files in usable js.

**Comment by chrisvander** [comment]
Is your app otherwise ES Module based?

**Comment by chrisvander** [comment]
If you are using Jest without ES Module support, but it is loading the `index.mjs` file, it implies to me that your `package.json` may be specifying that it is a module. Either way, I believe this is out of scope for the repository, unless you believe the `index.mjs` is being improperly loaded due to misconfiguration in this project.
