### ISSUE TITLE
Computed property that also relies on another computed property?

### ISSUE THREAD

**Issue by vincerubinetti** [chrisvander/zustand-computed#9]
Is it possible to have a computed property that relies on a regular state property and also another computed property? It seems like I'm able to access it just fine, but it's the previous value.

Here's a minimal reproducible example:
https://codesandbox.io/s/zustand-computed-chained-6fg57x?file=/src/index.ts

I suppose it opens up a can of worms for order of operations and weird cyclic/non-linear things (if we were to think of variable dependencies as a graph). But, for example, Vue `computed` enables you to do this type of computed "chaining". I'm not sure how it handles the messiness though.

Is there a way you recommend to handle this type of situation with your middleware?

**Comment by chrisvander** [comment]
That's interesting! In this case I would extract out your computed values into local variables inside the computed function before putting it back together. It is possible to listen for which variables are read from the passed-in State object via Proxy, and is may be possible to unravel the state graph and resolve cases of recursive dependency (maybe by using the previous value instead of requiring new computation), but that seems somewhat messy and fraught with assumptions.

An alternative I'm considering is passing multiple "computed" functions. If you have state A, B, C, and A is 
`{ value: number }`, B is `{ squared: number }`, and C is `{ cubed: number }`, you could have two functions that calculate A -> B and A&B -> C. In this small example, that may not read as nicely, or be necessary, but I can see complex state trees that may benefit from use of separate computed function (in case one is expensive and not always needed to be run).

I'll think on this, on honeymoon at the moment though 😁

**Comment by chrisvander** [comment]
At the moment, the simplest thing is to store any values that are part of the "computed" portion as variables within the function, and not rely on references all the way through. You may also want to split your state definitions into "State" and "ComputedState" as some of the examples show. This way, within the compute function, values like `state.doubled` should not exist on type State, but will exist coming out of the store.

This is the best way to do it for a function that's called every time. I could see building a dependency tree as a further way to deal with multiple relationships (some with more expense computations) but that isn't an immediate term thing.
